<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.422"/><!--comprimento chassis-->
    <xacro:property name="chassis_width" value="0.330"/><!--largura chassis-->
    <xacro:property name="chassis_height" value="0.100"/><!--altura chassis-->
    <xacro:property name="chassis_mass" value="6.000"/><!--massa chassis total 7.15 kg-->
    <xacro:property name="wheel_radius" value="0.050"/><!--raio roda-->
    <xacro:property name="wheel_thickness" value="0.027"/><!--espessura roda-->
    <xacro:property name="wheel_mass" value="0.525"/><!--massa roda-->
    <xacro:property name="wheel_radius_b" value="0.013"/><!--raio roda interior-->
    <xacro:property name="wheel_thickness_b" value="0.043"/><!--espessura roda interior-->
    <xacro:property name="wheel_offset_x" value="0.368"/><!--offset roda X-->
    <xacro:property name="wheel_offset_y" value="0.213"/><!--offset roda Y-->
    <xacro:property name="wheel_offset_z" value="-0.010"/><!--offset roda Z-->
    <xacro:property name="axis_radius" value="0.008"/><!--raio eixo-->
    <xacro:property name="axis_thickness" value="0.480"/><!--espessura eixo-->
    <xacro:property name="axis_mass" value="0.100"/><!--massa eixo-->
    <xacro:property name="axis_offset_x" value="0.368"/><!--offset eixo X-->
    <xacro:property name="axis_offset_y" value="0.000"/><!--offset eixo Y-->
    <xacro:property name="axis_offset_z" value="-0.010"/><!--offset eixo Z-->
    <xacro:property name="caster_wheel_radius" value="0.030"/><!--raio roda livre-->
    <xacro:property name="caster_wheel_mass" value="0.100"/><!--massa roda livre-->
    <xacro:property name="caster_wheel_offset_x" value="0.031"/><!--offset roda livre X-->
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

   
    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>




    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius_b}" length="${wheel_thickness_b}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius_b}" length="${wheel_thickness_b}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>




    <!-- AXIS LINK -->

    <joint name="axis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="axis"/>
        <origin xyz="0 ${-axis_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="axis">
        <visual>
            <geometry>
                <cylinder radius="${axis_radius}" length="${axis_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${axis_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${axis_mass}" length="${axis_thickness}" radius="${axis_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="axis">
        <material>Gazebo/Blue</material>
    </gazebo>





    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>